### ISSUE TITLE
comentarios

### ISSUE THREAD

**Issue by gastonprieto** [juanmpereira/Ej-QueMePongo#1]
Te dejo un par de comentarios:

https://github.com/juanmpereira/Ej-QueMePongo/blob/4aed81ccdee68702844401c1c04584898a18dc61/src/main/java/codigo/Horario.java#L40. ojo que muchas combinaciones pueden generar el mismo numero

Java 8 tiene una API de fechas mas nuevas que Calendar

https://github.com/juanmpereira/Ej-QueMePongo/blob/4aed81ccdee68702844401c1c04584898a18dc61/src/main/java/codigo/ClimaActual.java#L43 esto se lo podrías delegar a Horario, así no te queda un data clase. Mas allá de eso como te comentaba la API de fechas, existen formas de hacerlo un poco mas simple.
https://docs.oracle.com/javase/tutorial/datetime/iso/period.html (fijate la parte de period)

Algo de la clase clima actual que veo, es que esta sirviendo como interpretador de la API de climas y ademas de cache del resultado del clima, entonces tiene menor cohesión que si fueran 2 objetos distintos, uno que tiene cache y otro que entiende como devolver un objeto clima. 

A la clase clima actual, le pondria proveedorClima porque pareceria ser un caso particular del clima.

https://github.com/juanmpereira/Ej-QueMePongo/blob/4aed81ccdee68702844401c1c04584898a18dc61/src/main/java/codigo/ClimaActual.java#L11 ojo con esto que tal vez quisiste definir un constructor pero no es.

Un tema con el diseño del componente es que estaria bueno que te llegue parametrizada la ciudad aunque siempre se use la misma para las pruebas

Ojo con commitear los archivos autogenerados de eclipse

Estaba viendo el filtro de las prendas y vi que tenes un filtro de combinado, ojo que el usuario no definio si tenia que pasar esto y cual es el criterio, acordate de YAGNI

Para mi atuendo tiene en este caso como lo modelaste en la parte de creacion, resuelve algo del momento de uso. Tenemos que tratar de minimizar la lógica en los constructores. 

Me suena que la prenda no deberia tener el clima, porque es un dato de como es el clima actualmente que no parece ser el clima de la ropa. Me parece que el clima solo tiene sentido en el contexto del algoritmo que selecciona como se construye una prenda.

https://github.com/juanmpereira/Ej-QueMePongo/blob/4aed81ccdee68702844401c1c04584898a18dc61/src/main/java/codigo/Atuendo.java#L21 Ojo que esto no compila porque stream no es lo mismo que list y no podes pedirle el get(0), podrias por ejemplo si queres pedirle el primero que cumple usar findFirst()

**Comment by juanmpereira** [comment]
Ahi vi los comentarios y estuvo cambiando algunas cosas. De todos modos me gustaria saber bien como se utiliza el Duration. Yo pongo Duration.ofDays(1) y que es lo que me devuelve o guarda? 
Por otro lado, en la clase no se hablo del tema de verificar el tiempo para que no se cree 2 appiWeather en menos de 24 horas. Estaria bien la idea del singleton con un actualizador para cuando pasan 24 horas como habia planteado?

**Comment by juanmpereira** [comment]
Ahi actualice con como me iria quedando ahora, faltan algunas cosas pero esa es la idea principal. De todas formas espero tu respuesta a las preguntas anteriores para seguir modificandolo

**Comment by gastonprieto** [comment]
> Ahi vi los comentarios y estuvo cambiando algunas cosas. De todos modos me gustaria saber bien como se utiliza el Duration. Yo pongo Duration.ofDays(1) y que es lo que me devuelve o guarda?

Te devuelve un objeto duration que basicamente representa a 1 día pero sin referencia absoluta en el tiempo, es como la abstracción de 1 día y por ejemplo a un `Instant` le podrías sumar la duracion que hayas definido, se entiende la idea?

**Comment by gastonprieto** [comment]
> Por otro lado, en la clase no se hablo del tema de verificar el tiempo para que no se cree 2 appiWeather en menos de 24 horas. Estaria bien la idea del singleton con un actualizador para cuando pasan 24 horas como habia planteado?

Si, podrías usar un singleton por ejemplo para que sea una única instancia. 

Lo que si tenes que ver eso como se une con el diseño que quedo planteado en clase. y en donde pondrias lo de que se guarda, lo mas cohesivo seria tener otro objeto que se ponga adelante del Proveedor de Clima, porque sino esa lógica la vas a repetir en todos.

**Comment by juanmpereira** [comment]
> > Ahi vi los comentarios y estuvo cambiando algunas cosas. De todos modos me gustaria saber bien como se utiliza el Duration. Yo pongo Duration.ofDays(1) y que es lo que me devuelve o guarda?
> 
> Te devuelve un objeto duration que basicamente representa a 1 día pero sin referencia absoluta en el tiempo, es como la abstracción de 1 día y por ejemplo a un `Instant` le podrías sumar la duracion que hayas definido, se entiende la idea?

Perfecto, yo guardo el duration en una instancia "periodo" por ejemplo. Al mismo tiempo al inicializar guardo el LocalDate.now() en una instancia dia. Se que se puede hacer dia.plus(periodo) que calcula el momento en que termina ese periodo. Ahora la cuestion seria  como deberia hacer en el if de actualizarClima para ver si ya se cumplio ese periodo. Lo unico que se me ocurrio fue hacer if(LocalDate.now() != dia.plus(periodo) ) pero no esta bien comparar fechas de esta forma. Que otra solucion tengo para comparar esto?

**Comment by juanmpereira** [comment]
> > Por otro lado, en la clase no se hablo del tema de verificar el tiempo para que no se cree 2 appiWeather en menos de 24 horas. Estaria bien la idea del singleton con un actualizador para cuando pasan 24 horas como habia planteado?
> 
> Si, podrías usar un singleton por ejemplo para que sea una única instancia.
> 
> Lo que si tenes que ver eso como se une con el diseño que quedo planteado en clase. y en donde pondrias lo de que se guarda, lo mas cohesivo seria tener otro objeto que se ponga adelante del Proveedor de Clima, porque sino esa lógica la vas a repetir en todos.

Claro, entendi esta idea. Luego intentare hacer una unica instancia de proovedorClima para no tener que repetir la logica del singleton en todos los proovedores distintos que haya.

**Comment by gastonprieto** [comment]
> if(LocalDate.now() != dia.plus(periodo) ) pero no esta bien comparar fechas de esta forma. Que otra solucion tengo para comparar esto?

Perdon por responder tan tarde, pero después revisa la documentación de la fecha que tienen algunos mensajes que te pueden decir si ya paso una fecha o si es anterior.

**Comment by juanmpereira** [comment]
podria hacer algo asi: 
'LocalDate fechaActual = LocalDate.now();
if(fechaActual.compareTo(dia.plus(periodo))> 0 ) '

entonces si es mayor a 0 es por que la fechaActual es mayor, es decir, ya paso el tiempo.
Seria correcto hacerlo de esta forma?

**Comment by gastonprieto** [comment]
hola!

Si, se puede hacer pero es medio el feo el mensaje, fijate que las fechas tienen mensajes de mas alto nivel como isAfter o isBefore

https://www.geeksforgeeks.org/localdate-isbefore-method-in-java-with-examples/

**Comment by juanmpereira** [comment]
Perfecto, hago uso del isAfter entonces. Gracias
